name: Build kernel deb packages
on: push

jobs:
  build:
    name: Build kernel
    runs-on: vm
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Update Kernel
        id: update-kernel
        run: |
          latest_tag=$(curl -sS https://www.kernel.org/releases.json | jq -r '.latest_stable.version')
          echo "Latest Linux Kernel version: $latest_tag"
          echo "echo \"$latest_tag\" > temp_file.txt" >> create_file.sh
          chmod +x create_file.sh
          ./create_file.sh  # 执行脚本以创建临时文件1

      - name: Rename File
        run: |
          latest_tag=$(cat temp_file.txt)
          mv temp_file.txt "$latest_tag.txt"  # 将临时文件重命名为以版本号命名的文件


      - name: Build
        run: bash build_action.sh


      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
          
      - name: Commit and Push Changes
        if: steps.update-kernel.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config user.name "XXTXTOP"
          git config user.email "xxtxtop@gmail.com"
          ls -al
          pwd
          #git add /*.txt
          #git commit -m "Create file with kernel version"
          #git push origin testing

